server:
  port: 8080
  max-http-header-size: 100000

spring:
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    encoding: utf-8
    servlet:
      content-type: text/html
  datasource:
    name:
    url: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 
    password: 

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    call-setters-on-nulls: false

wps:
  wps-invite-path: https://zt.wps.cn/2018/clock_in/api/invite
